server:
  port: 9191
  
spring:
  application:    name: api-gateway
  cloud:    gateway:      routes:      - id: movie-catalogue-service
        uri: lb://movie-catalogue-service        predicates:        - Path=/moviecatalogue/**
    
eureka:  client:    service-url:      defaultZone: http://localhost:8761/eureka
  instance:    hostname: localhost
    
  